fix missing includes for fstat
In order for fstat to be usable, sys/stat.h needs to be included or we
might end up in a build failure like:

[..]/src/lib/libextractor.c:185:5: error: implicit declaration of function 'fstat' [-Werror=implicit-function-declaration]
|      if(-1 == fstat(fd, &s))
|      ^